language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  matrix:
   - DJANGO="Django>=1.10,<1.11"
   - DJANGO="Django>=1.11,<1.12"
branches:
    only:
        - master
# Start services.
services:
  - redis-server
# command to install dependencies
install:
  - pip install "$DJANGO"
  - pip install -r requirements/local.txt
  - pip install python-coveralls
  - pip install coverage
before_script:
  - cp .env.example .env
  - python manage.py migrate
  - python manage.py collectstatic --noinput
# command to run tests
script:
    - pytest
after_success:
    - coveralls
