# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20180113_2139'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileitem',
            name='user',
        ),
        migrations.AddField(
            model_name='fileitem',
            name='feed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feed_media', to='feeds.Feed'),
        ),
    ]
