# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20180113_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='url',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
